# federation_version: 2
# subgraphs:
#   auth:
#     routing_url: http://localhost:3003/graphql
#     schema:
#       subgraph_url: http://localhost:3003/graphql
#   users:
#     routing_url: http://localhost:3000/graphql
#     schema:
#       subgraph_url: http://localhost:3000/graphql
#   students:
#     routing_url: http://localhost:3001/graphql
#     schema:
#       subgraph_url: http://localhost:3001/graphql
#   applications:
#     routing_url: http://localhost:3004/graphql
#     schema:
#       subgraph_url: http://localhost:3004/graphql

federation_version: 2
subgraphs:
  auth:
    routing_url: https://accounts.demo.starstuff.dev
    schema:
      subgraph_url: https://accounts.demo.starstuff.dev
  users:
    routing_url: https://inventory.demo.starstuff.dev
    schema:
      subgraph_url: https://inventory.demo.starstuff.dev
  students:
    routing_url: https://products.demo.starstuff.dev
    schema:
      subgraph_url: https://products.demo.starstuff.dev
  applications:
    routing_url: https://reviews.demo.starstuff.dev
    schema:
      subgraph_url: https://reviews.demo.starstuff.dev
